[workspace]
members = ["crates/controlplane", "crates/dataplane", "crates/gateway-crds"]
resolver = "3"

[workspace.dependencies]
kube = { version = "2.0", default-features = false, features = [
  "runtime",
  "derive",
  "client",
  "rustls-tls",
  "aws-lc-rs",
] }
k8s-openapi = { version = "0.26", features = ["latest", "schemars"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
