apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: multiway
  labels:
    app.kubernetes.io/name: multiway
spec:
  controllerName: io.multiway/gateway-controller
  description: Gateway API implementation using Pingora data plane
